# Approved Application Authentication Credentials
approvedKeys:
  - application: application
    secret: secret

# Server configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: config/dev-server.jks
      keyStorePassword: password
      validateCerts: false
      validatePeers: false

  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: config/dev-server.jks
      keyStorePassword: password
      validateCerts: false
      validatePeers: false